### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by lulebe** [lulebe/jscrusades#5] opened 2022-03-24 00:46 UTC
The main thing left to do now: 

**Port over the original AI. Massive Task, lets do it!**

**Comment by lulebe** [comment] 2022-04-20 16:00
Campaign Map 3 freezes on first Ai turn

**Comment by Simsso** [comment] 2022-05-03 13:10
Can't reproduce the issue at http://localhost:8080/game#save=-1;map=23;mode=2

Can we close this issue as completed?

**Closed as completed** 2022-05-03 23:29 UTC
Labels: feature
